import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'

function HomeDynamic() {
	const router = useRouter()
	const { id } = router.query

	return (
		<div>
			<Head>
				<title>{id}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			{id}
		</div>
	)
}

export default HomeDynamic
