import Head from 'next/head'
import styles from '../styles/Home.module.css'
import salesData from '../MOCK_CART_EXO_4.json'
import Header from '../components/header'
import OptionSelector, { options } from '../components/optionSelector'
import SalesCard from '../components/salesCard'
import { useState } from 'react'

export async function getStaticProps(context) {
	return {
		props: { sales: salesData }
	}
}

export default function Home(props) {
	const [selectedOption, setSelectedOption] = useState(options.SALES)
	console.log(selectedOption)
	const handleOptionChange = (option) => {
		setSelectedOption(option)
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Carts</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<Header title={'In-Store History'} />
				<OptionSelector onOptionChange={handleOptionChange} />
				{props.sales?.length && (
					<>
						<div className={styles.salesLayout}>
							{props.sales
								.filter((sale) => {
									return (
										(sale.status === 'SENT_TO_POS' &&
											selectedOption === options.TILL) ||
										(sale.status !== 'SENT_TO_POS' &&
											selectedOption === options.SALES)
									)
								})
								.map((sale) => {
									console.log(sale)
									return (
										<SalesCard
											key={sale.orderId}
											sale={sale}
											href={`/cart-detail/${sale.orderId}`}
										/>
									)
								})}
						</div>
					</>
				)}
			</main>
		</div>
	)
}
